// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.DTO
{
    public partial class AuditLogDto
    {
        public decimal Id { get; set; }
        public decimal? AccountId { get; set; }
        public string AccountName { get; set; }
        public int? ActionType { get; set; }
        public DateTime? CreateDate { get; set; }
        public string TableName { get; set; }
        public decimal? RecordId { get; set; }
        public string ActionTypeName { get; set; }

    }
}