// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class AccountRole
    {
        public int Id { get; set; }
        public string AccountGuid { get; set; }
        public int? AccountId { get; set; }
        public string CodeNo { get; set; }

        public virtual Account1 Account { get; set; }
    }
}