// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class Account
    {
        public decimal Id { get; set; }
        public string HallGuid { get; set; }
        public string Uid { get; set; }
        public string Upwd { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string AccountRfid { get; set; }
        public string AccountRole { get; set; }
        public string AccountLevel { get; set; }
        public string AccountGroup { get; set; }
        public string LicensePath { get; set; }
        public string PhotoPath { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? Lastlogin { get; set; }
        public DateTime? Lastuse { get; set; }
        public string Comment { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public DateTime? DeleteDate { get; set; }
        public decimal? DeleteBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
        public string PageSizeSetting { get; set; }
    }
}