// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class BookingTypeC
    {
        public decimal Id { get; set; }
        public string UpperGuid { get; set; }
        public DateTime? ChantingDate { get; set; }
        public string ChantingType { get; set; }
        public string InOut { get; set; }
        public decimal? MageMonk { get; set; }
        public decimal? HouseMonk { get; set; }
        public string Offerings { get; set; }
        public string MageMemo { get; set; }
        public string MageMoney { get; set; }
        public decimal? AccountGuid { get; set; }
    }
}