// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class BookingFruit
    {
        public decimal Id { get; set; }
        public string UpperGuid { get; set; }
        public DateTime? FruitDate { get; set; }
        public string PrepareRice { get; set; }
        public string PrepareVegetarian { get; set; }
        public string PrepareFlower { get; set; }
        public string PrepareFruit { get; set; }
        public string PrepareTea { get; set; }
        public decimal? AccountGuid { get; set; }
    }
}