// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class Booking2Time
    {
        public decimal Id { get; set; }
        public string BookingGuid { get; set; }
        public string BookingTime { get; set; }
        public string CodeNo { get; set; }
    }
}