// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class CodeType1
    {
        public int Id { get; set; }
        public string Guid { get; set; }
        public string Code { get; set; }
        public string CodeNo { get; set; }
        public string CodeNameTw { get; set; }
        public string CodeNameEn { get; set; }
        public string CodeName2 { get; set; }
        public string CodeName3 { get; set; }
        public string CodeName4 { get; set; }
        public string Comment { get; set; }
        public string InsertDatetime { get; set; }
        public string UpdateDatetime { get; set; }
        public string InsertBy { get; set; }
        public string UpdateBy { get; set; }
        public string DeleteBy { get; set; }
        public string DeleteDatetime { get; set; }
        public string Status { get; set; }
    }
}