// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class DbPublicFavorite
    {
        public decimal Id { get; set; }
        public string UpperGuid { get; set; }
        public string AccountGuid { get; set; }
        public string Status { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}