// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class DeviceError
    {
        public decimal Id { get; set; }
        public string DeviceGuid { get; set; }
        public string DeviceL { get; set; }
        public string DeviceR { get; set; }
        public string ErrorType { get; set; }
        public string ErrorText { get; set; }
        public string PhotoPath { get; set; }
        public string MemberGuid { get; set; }
        public string LandLordGuid { get; set; }
        public string EngineerGuid { get; set; }
        public string Comment { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public DateTime? DeleteDate { get; set; }
        public decimal? DeleteBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
    }
}