// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class Electrician
    {
        public decimal Id { get; set; }
        public string SiteGuid { get; set; }
        public string Uid { get; set; }
        public string Upwd { get; set; }
        public string ElectricianNo { get; set; }
        public string ElectricianName { get; set; }
        public string ElectricianIdcard { get; set; }
        public string LicensePath { get; set; }
        public string PhotoPath { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? Lastlogin { get; set; }
        public DateTime? Lastuse { get; set; }
        public string Comment { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public DateTime? DeleteDate { get; set; }
        public decimal? DeleteBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
        public string ElectricianSex { get; set; }
        public DateTime? ElectricianBirthday { get; set; }
        public string ElectricianEmail { get; set; }
        public string ElectricianMobile { get; set; }
        public string ElectricianAddress { get; set; }
    }
}