// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class Employee
    {
        public decimal Id { get; set; }
        public string AccountGuid { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeNo { get; set; }
        public decimal? EmployeeSex { get; set; }
        public DateTime? EmployeeBirthday { get; set; }
        public string EmployeeNickname { get; set; }
        public string EmployeeTel { get; set; }
        public string EmployeeMobile { get; set; }
        public string EmployeeAddress { get; set; }
        public string EmployeeAddressDomicile { get; set; }
        public string EmployeeIdcard { get; set; }
        public string EmployeeEmail { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string EmployeeUnit { get; set; }
        public string EmployeeDept { get; set; }
        public string EmployeeLevel { get; set; }
        public string ContactName { get; set; }
        public string ContactTel { get; set; }
        public string Comment { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public DateTime? DeleteDate { get; set; }
        public decimal? DeleteBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
    }
}