// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class HallTime
    {
        public decimal Id { get; set; }
        public string SiteGuid { get; set; }
        public string HallGuid { get; set; }
        public string Start { get; set; }
        public string End { get; set; }
    }
}