// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class Member
    {
        public decimal Id { get; set; }
        public string SiteGuid { get; set; }
        public string Uid { get; set; }
        public string Upwd { get; set; }
        public string MemberNo { get; set; }
        public string MemberName { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? Lastlogin { get; set; }
        public DateTime? Lastuse { get; set; }
        public string Comment { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public DateTime? DeleteDate { get; set; }
        public decimal? DeleteBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
           public string MemberSex { get; set; }
        public DateTime? MemberBirthday { get; set; }
        public string MemberIdcard { get; set; }
        public string MemberEmail { get; set; }
        public string MemberMobile { get; set; }
        public string MemberAddress { get; set; }
        public string MemberLine { get; set; }
        public string CarGuid { get; set; }
        public string CarName { get; set; }
        public string CarNumber { get; set; }
        public string CarVIN { get; set; }
        public string PaymentGuid { get; set; }
        public string PhotoPath { get; set; }
        public string MemberStatus { get; set; }
        public string LastLocation { get; set; }
        public string RoleType { get; set; }
        public bool? CarLicenseCheck { get; set; }
        public string IdCard1Path { get; set; }
        public string IdCard2Path { get; set; }
        

    }
}