// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class MultiChoiceCountyTownShip
    {
        public decimal Id { get; set; }
        public string UpperGuid { get; set; }
        public string CountyId { get; set; }
        public string TownShipId { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
    }
}