// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class ParkingLot
    {
        public decimal Id { get; set; }
        public string SiteGuid { get; set; }
        public string ParkingLotType { get; set; }
        public string ParkingLotNo { get; set; }
        public string ParkingLotName { get; set; }
        public string DeviceGuid { get; set; }
        public string DeviceLr { get; set; }
        public string Comment { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public DateTime? DeleteDate { get; set; }
        public decimal? DeleteBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
    }
}