// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class Pricing
    {
        public int Id { get; set; }
        public string ContentZh { get; set; }
        public string ContentEn { get; set; }
        public string ContentVi { get; set; }
    }
}