// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class PublicCountyTownShip
    {
        public int Id { get; set; }
        public string CountryId { get; set; }
        public string TownShip { get; set; }
        public string UpperGuid { get; set; }
        public string CancelFlag { get; set; }
        public string Guid { get; set; }
    }
}