// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class ReportError
    {
        public decimal Id { get; set; }
        public string DeviceGuid { get; set; }
        public string Guid { get; set; }
        public string DeviceLeftGuid { get; set; }
        public string DeviceRightGuid { get; set; }
        public string ErrorType { get; set; }
        public string ErrorDetail { get; set; }
        public DateTime? ErrorFixedDate { get; set; }
        public string ErrorFixedDetail { get; set; }
    }
}