// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class ReportConfig
    {
        public int Id { get; set; }
        public string Slpage { get; set; }
        public string Sltype { get; set; }
        public string Slkey { get; set; }
        public string Comment { get; set; }
        public string Sltw { get; set; }
        public string Slen { get; set; }
        public string Slcn { get; set; }
        public string Slvn { get; set; }
        public string SystemMenuGuid { get; set; }
        public decimal? Sequence { get; set; }
        public decimal? ColumnWidth { get; set; }
        public string TextAlign { get; set; }
        public string Paddingtop { get; set; }
        public string Paddingbottom { get; set; }
        public string Paddingleft { get; set; }
        public string Paddingright { get; set; }
    }
}