// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class SysLogSp
    {
        public decimal SluId { get; set; }
        public string SluSp { get; set; }
        public DateTime? SluDate { get; set; }
    }
}