// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class SysLogDuty
    {
        public decimal Id { get; set; }
        public string Type { get; set; }
        public string Ip { get; set; }
        public string Wip { get; set; }
        public DateTime? Date { get; set; }
        public string Time { get; set; }
    }
}