// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class User2Message
    {
        public decimal Id { get; set; }
        public string UserGuid { get; set; }
        public string Type { get; set; }
        public string Icon { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string Link { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? ReadDate { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
    }
}