// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class UserView
    {
        public string Accountid { get; set; }
        public string Fullname { get; set; }
        public string Deptid { get; set; }
        public string Deptname { get; set; }
        public string Titlecaption { get; set; }
        public string IsFuneralDirector { get; set; }
        public string StatusType { get; set; }
        public string Email { get; set; }
        public DateTime? InsDate { get; set; }
    }
}