// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class XAccountSetting
    {
        public decimal Id { get; set; }
        public string AccountGuid { get; set; }
        public string Page { get; set; }
        public string ControllerName { get; set; }
        public string ControllerValue { get; set; }
    }
}