// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.DTO
{
    public partial class DiscountDto
    {
        public decimal Id { get; set; }
        public string MemberGuid { get; set; }
        public string SiteGuid { get; set; }

        public string DiscountTitle { get; set; }

        public string DiscountBody1 { get; set; }
        public string DiscountBody2 { get; set; }
        public DateTime? DiscountDeadline { get; set; }
        public string DiscountLocation { get; set; }
        public string Comment { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public DateTime? DeleteDate { get; set; }
        public decimal? DeleteBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
    }
}