// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;

namespace Evse.DTO
{
    public partial class EngineerDto
    {
        public decimal Id { get; set; }
        public string SiteGuid { get; set; }
        public string Uid { get; set; }
        public string Upwd { get; set; }
        public string EngineerNo { get; set; }
        public string EngineerName { get; set; }
        public string EngineerIdcard { get; set; }
        public string LicensePath { get; set; }
        public string PhotoPath { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? Lastlogin { get; set; }
        public DateTime? Lastuse { get; set; }
        public string Comment { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public DateTime? DeleteDate { get; set; }
        public decimal? DeleteBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }

        public string EngineerSex { get; set; }
        public DateTime? EngineerBirthday { get; set; }
        public string EngineerEmail { get; set; }
        public string EngineerMobile { get; set; }
        public string EngineerAddress { get; set; }
        public string EngineerSexName { get; set; }
        public List<IFormFile> File { get; set; }

    }
}