// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;

namespace Evse.DTO
{
    public partial class LandLordDto
    {
        public decimal Id { get; set; }
        public string SiteGuid { get; set; }
        public string Uid { get; set; }
        public string Upwd { get; set; }
        public string LandLordNo { get; set; }
        public string LandLordName { get; set; }
        public string LandLordIdcard { get; set; }
        public string LicensePath { get; set; }
        public string PhotoPath { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? Lastlogin { get; set; }
        public DateTime? Lastuse { get; set; }
        public string Comment { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public DateTime? DeleteDate { get; set; }
        public decimal? DeleteBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }

        
        public string LandLordSex { get; set; }
        public DateTime? LandLordBirthday { get; set; }
        public string LandLordEmail { get; set; }
        public string LandLordMobile { get; set; }
        public string LandLordAddress { get; set; }
        public string ContractGuid { get; set; }
        public string BankGuid { get; set; }
        public List<IFormFile> File { get; set; }
        public string LandLordSexName { get; set; }

    }
}