import { Record2Pig } from "src/app/_core/_model/apply-orders";

export class Breeding2SowConst {
  static readonly SowBodyCondition = "Sow_BodyCondition";
  static readonly SowFarrow = "Sow_Farrow";
  static readonly SowIn = "Sow_In";
  static readonly SowFoster = "Sow_Foster";
  static readonly SowHeating = "Sow_Heating";
  static readonly SowMating = "Sow_Mating";
  static readonly SowPreFarrow = "Sow_PreFarrow";
  static readonly SowPregnancyTest = "Sow_PregnancyTest";
  static readonly SowWeaning = "Sow_Weaning";
  static readonly SowAbortion = "Sow_Abortion";

 static readonly SucklingCastration = "Suckling_Castration";
 static readonly SucklingCutEar = "Suckling_CutEar";
 static readonly SucklingCutTeethTail = "Suckling_CutTeethTail";
 static readonly SucklingIronInjection = "Suckling_IronInjection";
 static readonly SucklingMove = "Suckling_Move";
 static readonly SucklingTeachingSlot = "Suckling_TeachingSlot";
 static readonly SucklingWeaning = "Suckling_Weaning";
 static readonly SucklingWeighing = "Suckling_Weighing";
 static readonly Breeding2SowIn = "Breeding2_SowIn"

}
export interface NewBoarIn {
  id: number;
  farmGuid: string;
  type: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: any | null;
  updateBy: number | null;
  deleteDate: any | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  veterinaryDate: any | null;
  veterinaryReason: string;
  veterinaryGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  inOutNo: string;
  inOutName: string;
  fromFarm: string;
  toFarm: string;
  pigInfor: string;
  inOutReason: string;
  inOutSource: string;
  inOutDept: string;
  inOutAmount: number | null;
  inOutWeight: number | null;
  sourceOrderNo: string;
  sourceAmount: number | null;
  sourceTotalWeight: number | null;
  realAmount: number | null;
  realTotalWeight: number | null;
  pigs: any;
  pens: any;
  roomGuid: any;
  penGuid: any;
  breeding2GiltIns: any;
  breedingGuid: any
 makeOrderGuid: any
}
export interface NewBoarInOld {
  id: number;
  farmGuid: string;
  type: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: any | null;
  updateBy: number | null;
  deleteDate: any | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  announceGuid: string;
}
export interface Boar2SemenMix {
  id: number;
  type: string;
  recordGuid: string;
  sourceGuid: string;
  semenVolume: number | null;
  semenConcentration: number | null;
  spermMotility: number | null;
  spermColor: string;
  malformationRate: number | null;
  malformationHead: number | null;
  malformationMiddle: number | null;
  malformationTail: number | null;
  sourceGuidName: string;
}
export interface SowSilo {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any| null;
  applyDate: any| null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any| null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  agreeDate: any| null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  executeAmount: number | null;
  executeFeedGuid: string;
  estAmount: number | null;
  remainingAmount: number | null;
  realAmount: number | null;
  feedCost: number | null;
  recordNo: string;
  medicineGuid: string;
  treatmentGuid: string;
  typeName: string;
  statusName: string;
  pigs: string[];
  roomGuid: string;
  penGuid: string;
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
  makeOrderName: string;
  makeOrderNo: string;
}
export interface SowRotation {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any| null;
  applyDate: any| null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any| null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  deathMethod: number | null;
  deathReason: string;
  deathWeight: number | null;
  agreeDate: any| null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  disaster: string;
  deathQty: number | null;
  deathReasonName: string;
  typeName: string;
  pigs: string[];
  record2Pigs: Record2Pig[];
  statusName: string;
  pens: string[];
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
  makeOrderName: string;
  makeOrderNo: string;
  afterRoomGuid: string;
  afterPenGuid: string;
}

export interface SowQuarantine {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any| null;
  applyDate: any| null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any| null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  deathMethod: number | null;
  deathReason: string;
  deathWeight: number | null;
  agreeDate: any| null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  disaster: string;
  deathQty: number | null;
  deathReasonName: string;
  typeName: string;
  pigs: string[];
  record2Pigs: Record2Pig[];
  statusName: string;
  pens: string[];
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
  makeOrderName: string;
  makeOrderNo: string;
}
export interface SowFeeding {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any| null;
  applyDate: any| null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any| null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  feedGuid: string;
  useType: string;
  useUnit: string;
  frequency: string;
  estAmount: number | null;
  recordAmount: number | null;
  recordResult: string;
  agreeDate: any| null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  makeOrderAmound: number | null;
  makeOrderDayAge: number | null;
  intakeStandard: number | null;
  intakeReal: number | null;
  intakeAverage: number | null;
  deathReasonName: string;
  typeName: string;
  pigs: string[];
  record2Pigs: Record2Pig[];
  statusName: string;
  pens: string[];
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
  makeOrderName: string;
  makeOrderNo: string;
}
export interface SowBackFat {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any| null;
  applyDate: any| null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any| null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  deathMethod: number | null;
  deathReason: string;
  deathWeight: number | null;
  agreeDate: any| null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  disaster: string;
  deathQty: number | null;
  deathReasonName: string;
  typeName: string;
  pigs: string[];
  record2Pigs: Breeding2GiltIn[];
  statusName: string;
  pens: string[];
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
  makeOrderName: string;
  makeOrderNo: string;
}
export interface GiltTesting {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any| null;
  applyDate: any| null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any| null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  deathMethod: number | null;
  deathReason: string;
  deathWeight: number | null;
  agreeDate: any| null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  disaster: string;
  deathQty: number | null;
  deathReasonName: string;
  typeName: string;
  pigs: string[];
  record2Pigs: Record2Pig[];
  statusName: string;
  pens: string[];
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
  makeOrderName: string;
  makeOrderNo: string;
}
export interface BoarTesting {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any| null;
  applyDate: any| null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any| null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  deathMethod: number | null;
  deathReason: string;
  deathWeight: number | null;
  agreeDate: any| null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  disaster: string;
  deathQty: number | null;
  deathReasonName: string;
  typeName: string;
  pigs: string[];
  record2Pigs: Record2Pig[];
  statusName: string;
  pens: string[];
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
  makeOrderName: string;
  makeOrderNo: string;
}
export interface BoarSilo {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any| null;
  applyDate: any| null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any| null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  agreeDate: any| null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  executeAmount: number | null;
  executeFeedGuid: string;
  estAmount: number | null;
  remainingAmount: number | null;
  realAmount: number | null;
  feedCost: number | null;
  recordNo: string;
  medicineGuid: string;
  treatmentGuid: string;
  typeName: string;
  statusName: string;
  pigs: string[];
  roomGuid: string;
  penGuid: string;
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
}
export interface BoarSemenTesting {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any| null;
  applyDate: any| null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any| null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  deathMethod: number | null;
  deathReason: string;
  deathWeight: number | null;
  agreeDate: any| null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  disaster: string;
  deathQty: number | null;
  deathReasonName: string;
  typeName: string;
  pigs: string[];
  record2Pigs: Record2Pig[];
  statusName: string;
  pens: string[];
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
  makeOrderName: string;
  makeOrderNo: string;

  pigGuid: string;
  idno: string;
  earNo: string;
  earTag: string;
  rfidtag: string;
  semenVolume: number | null;
  semenConcentration: number | null;
  spermMotility: number | null;
  spermColor: string;
  malformationRate: number | null;
}
export interface BoarQuarantine {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  upperRecord: string;
  upperGuid: string;
  estDate: any | null;
  comment: string;
  createDate: any | null;
  createBy: number | null;
  updateDate: any | null;
  updateBy: number | null;
  deleteDate: any | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  deathReasonName: string;
  typeName: string;
  pigs: string[];
  record2Pigs: Record2Pig[];
  statusName: string;
  pens: string[];
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
  makeOrderName: string;
  makeOrderNo: string;
  penGuid: string;
  roomGuid: string;
}
export interface BoarSemenMix {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any| null;
  applyDate: any| null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any| null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  deathMethod: number | null;
  deathReason: string;
  deathWeight: number | null;
  agreeDate: any| null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  disaster: string;
  deathQty: number | null;
  deathReasonName: string;
  typeName: string;
  pigs: string[];
  record2Pigs: Record2Pig[];
  statusName: string;
  pens: string[];
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
  makeOrderName: string;
  makeOrderNo: string;
  volumeUse: string;
  source1Guid: string;
  source2Guid: string;
  source3Guid: string;
}
export interface BoarRotation {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any| null;
  applyDate: any| null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any| null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  deathMethod: number | null;
  deathReason: string;
  deathWeight: number | null;
  agreeDate: any| null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  disaster: string;
  deathQty: number | null;
  deathReasonName: string;
  typeName: string;
  pigs: string[];
  record2Pigs: Record2Pig[];
  statusName: string;
  pens: string[];
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
  makeOrderName: string;
  makeOrderNo: string;
}

export interface BoarRide {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any| null;
  applyDate: any| null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any| null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  deathMethod: number | null;
  deathReason: string;
  deathWeight: number | null;
  agreeDate: any| null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  disaster: string;
  deathQty: number | null;
  deathReasonName: string;
  typeName: string;
  pigs: string[];
  record2Pigs: Record2Pig[];
  statusName: string;
  pens: string[];
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
  makeOrderName: string;
  makeOrderNo: string;
  pigGuid: string;
  idno: string;
  earNo: string;
  earTag: string;
  rfidtag: string;
  volume: number | null;
  ability: string;
  strength: string;
}
export interface BoarHeating {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any| null;
  applyDate: any| null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any| null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  deathMethod: number | null;
  deathReason: string;
  deathWeight: number | null;
  agreeDate: any| null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  disaster: string;
  deathQty: number | null;
  deathReasonName: string;
  typeName: string;
  pigs: string[];
  record2Pigs: Record2Pig[];
  statusName: string;
  pens: string[];
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
  makeOrderName: string;
  makeOrderNo: string;
}
export interface BoarFeeding {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any| null;
  applyDate: any| null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any| null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  feedGuid: string;
  useType: string;
  useUnit: string;
  frequency: string;
  estAmount: number | null;
  recordAmount: number | null;
  recordResult: string;
  agreeDate: any| null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  makeOrderAmound: number | null;
  makeOrderDayAge: number | null;
  intakeStandard: number | null;
  intakeReal: number | null;
  intakeAverage: number | null;
  deathReasonName: string;
  typeName: string;
  pigs: string[];
  record2Pigs: Record2Pig[];
  statusName: string;
  pens: string[];
  applyName: string;
  agreeName: string;
  rejectName: string;
  executeName: string;
  roomName: string;
  orderNo: string;
  disaster: string;
  deathQty: number | null;
  makeOrderName: string;
  makeOrderNo: string;
}

export interface Breeding2GiltIn {
  id: number;
  type: string;
  recordGuid: string;
  penGuid: string;
  giltGuid: string;
  giltGuidName: string;
  giltNo: string;
  bodyConditionLevel: string;
  bodyConditionLevelName: string;
  sowBackFat: string;
  sowBackFatName: string;
  dayAge: number;

}
export interface GiltIn {
  id: number;
  farmGuid: string;
  type: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: any | null;
  updateBy: number | null;
  deleteDate: any | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  veterinaryDate: any | null;
  veterinaryReason: string;
  veterinaryGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  inOutNo: string;
  inOutName: string;
  fromFarm: string;
  toFarm: string;
  pigInfor: string;
  inOutReason: string;
  inOutSource: string;
  inOutDept: string;
  inOutAmount: number | null;
  inOutWeight: number | null;
  sourceOrderNo: string;
  sourceAmount: number | null;
  sourceTotalWeight: number | null;
  realAmount: number | null;
  realTotalWeight: number | null;
  pigs: any;
  pens: any;
  roomGuid: any;
  penGuid: any;
  breeding2GiltIns: any;
  breedingGuid: any
 makeOrderGuid: any
}
export interface Environment {
    production: boolean;
    apiUrl: string;
    versionCheckURL: string;
    domain: string;
}
export interface BomGilt {
  id: number;
  bomNo: string;
  bomName: string;
  bomVersion: string;
  bomBreed: string;
  bomType: string;
  quarantineDays: number | null;
  bodyConditionLevel: string;
  sowBackFat: string;
  comment: string;
  cancelFlag: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  status: number | null;
  guid: string;
  applyEveryMonth: number;
  applyEveryDay: number;
}
export interface BomBoar {
  id: number;
  bomNo: string;
  bomName: string;
  bomVersion: string;
  bomBreed: string;
  bomType: string;
  semenVolume: number | null;
  semenConcentration: number | null;
  spermMotility: string;
  spermColor: string;
  malformationHead: number | null;
  malformationMiddle: number | null;
  malformationTail: number | null;
  rideDesire: string;
  rideHindLeg: string;
  comment: string;
  cancelFlag: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  status: number | null;
  guid: string;
  applyEveryMonth: number;
  applyEveryDay: number;
}
export interface BomSow {
  id: number;
  bomNo: string;
  bomName: string;
  bomVersion: string;
  bomBreed: string;
  bomType: string;
  sowHeatingStartDate: number | null;
  sowHeatingEndDate: number | null;
  sowMatingStartDate: number | null;
  sowMatingEndDate: number | null;
  sowPregnancyTest1StartDate: number | null;
  sowPregnancyTest1EndDate: number | null;
  sowMoveStartDate: number | null;
  sowMoveEndDate: number | null;
  sowPregnancyTest2StartDate: number | null;
  sowPregnancyTest2EndDate: number | null;
  sowBodyConditionStartDate: number | null;
  sowBodyConditionEndDate: number | null;
  sowPreFarrowStartDate: number | null;
  sowPreFarrowEndDate: number | null;
  sowFarrowStartDate: number | null;
  sowFarrowEndDate: number | null;
  sowMilkingStartDate: number | null;
  sowMilkingEndDate: number | null;
  sowWeaningStartDate: number | null;
  sowWeaningEndDate: number | null;
  pregnancyFeed1StartDate: number | null;
  pregnancyFeed1EndDate: number | null;
  pregnancyFeed1Amount: number | null;
  pregnancyFeed2StartDate: number | null;
  pregnancyFeed2EndDate: number | null;
  pregnancyFeed2Amount: number | null;
  pregnancyFeed3StartDate: number | null;
  pregnancyFeed3EndDate: number | null;
  pregnancyFeed3Amount: number | null;
  sucklingTeachingSlotStartDate: number | null;
  sucklingTeachingSlotEndDate: number | null;
  sucklingTeachingSlotAmount: number | null;
  comment: string;
  cancelFlag: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  status: number | null;
  guid: string;
  typeName: string;
  applyEveryMonth: number;
  applyEveryDay: number;
}
export interface Breeding2Suckling {
  id: number;
  type: string;
  breedingGuid: string;
  sowGuid: string;
  farrowGuid: string;
  sucklingGuid: string;
  sucklingEarNo: string | null;
  sucklingCutEar: string | null;
  sucklingWeighing: string | null;
  sucklingWeight: number | null;
  sucklingCutTeethTail: string | null;
  sucklingIronInjection: string | null;
  sucklingCastration: string | null;
  sucklingFoster: string | null;
  sucklingTeachingSlot: string | null;
  sucklingWeaning: string | null;
  sucklingMove: string | null;
  sucklingAmount: number | null;
  sucklingDisease: string;
  sucklingNext: string;
  sucklingNextPen: string;
  roomGuid: string;
  afterroomGuid: string;
  penGuid: string;
  sucklingNextArea: string;
  sucklingNextBarn: string;
  sucklingNextRoom: string;
}
export interface Breeding2SowBodyCondition {
  id: number;
  type: string;
  recordGuid: string;
  giltNo: string;
  giltGuid: string;
  roomGuid: string;
  penGuid: string;
  bodyConditionLevel: number | null;
}
export interface Breeding2SowBackFat {
  id: number;
  type: string;
  recordGuid: string;
  giltNo: string;
  giltGuid: string;
  roomGuid: string;
  penGuid: string;
  sowBackFat: number | null;
}
export interface SowIn {
  id: number;
  farmGuid: string;
  breedingGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  executeGuidName: string;
  breedingGuidName: string;
  breeding2Sow: Breeding2SowIn[];
}
export interface Breeding2SowIn {
  id: number;
  type: string;
  guid: string;
  penGuid: string;
  penGuidName: string;
  breedingGuid: string;
  recordGuid: string;
  sowGuid: string;
  breedingType: string;
  breedingStatus1: string;
  breedingStatus2: string;
  lastStatus: string;
  lastResult: string;
  parity: number | null;
  heatingDate: any | null;
  heatingResult: string;
  matingDate: any | null;
  matingAccount: string;
  semenGuid: string;
  roomGuid: string;
  sowGuidName: string;
  lastStatusName: string;
}
export interface Breeding2Sow {
  id: number;
  type: string;
  penGuid: string;
  breedingGuid: string;
  recordGuid: string;
  sowGuid: string;
  sowNext: string;
  level: string;
  heatingResult: string;
  matingDate: string | null;
  heatingPush: any | null;
  heatingWay: string | null;
  matingAccount: string;
  semenGuid: string;
  testResult: string;
  beforePenGuid: string;
  afterPenGuid: string;
  sucklingGuid: string;
  sucklingStatus: string;
  sowFosterGuid: string;
  fosterPenGuid: string;
  qtyCulling: number | null;
  cullingReason: string;
  levelName: string;
  heatingResultName: string;
  testResultName: string;
  typeName: string;
  semenGuidName: string;
  beforePenGuidName: string;
  afterPenGuidName: string;
  sucklingGuidName: string;
  breedingGuidName: string;
  penGuidName: string;
  sowGuidName: string;
  matingAccountName: string;
  abortionReason: string;
  abortionParity: number | null;
  abortionLastStatus: string;
  nextRoom: string;
  nextPen: string;
  abortiionDate: string | null;

}

export interface BreedingSowHeating {
    id: number;
    farmGuid: string;
    pigGuid: string;
    breedingGuid: string;
    executeDate: any| null;
    executeReason: string;
    executeGuid: string;
    comment: string;
    createDate: string | null;
    createBy: number | null;
    updateDate: string | null;
    updateBy: number | null;
    deleteDate: string | null;
    deleteBy: number | null;
    status: number | null;
    guid: string;
}
export interface BreedingSowMating {
    id: number;
    farmGuid: string;
    pigGuid: string;
    breedingGuid: string;
    executeDate: any| null;
    executeReason: string;
    executeGuid: string;
    comment: string;
    createDate: string | null;
    createBy: number | null;
    updateDate: string | null;
    updateBy: number | null;
    deleteDate: string | null;
    deleteBy: number | null;
    status: number | null;
    guid: string;
}
export interface BreedingSowPick {
    id: number;
    farmGuid: string;
    pigGuid: string;
    breedingGuid: string;
    executeDate: any| null;
    executeReason: string;
    executeGuid: string;
    comment: string;
    createDate: string | null;
    createBy: number | null;
    updateDate: string | null;
    updateBy: number | null;
    deleteDate: string | null;
    deleteBy: number | null;
    status: number | null;
    guid: string;
}
export interface BreedingSowPregnancyTest {
    id: number;
    farmGuid: string;
    pigGuid: string;
    breedingGuid: string;
    executeDate: any| null;
    executeReason: string;
    executeGuid: string;
    comment: string;
    createDate: string | null;
    createBy: number | null;
    updateDate: string | null;
    updateBy: number | null;
    deleteDate: string | null;
    deleteBy: number | null;
    status: number | null;
    guid: string;
}
export interface Breeding {
  id: number;
  farmGuid: string;
  roomGuid: string;
  pigType: string;
  type: string;
  breedingGroup: string;
  breedingNo: string;
  breedingName: string;
  breedingDate: string | null;
  breedingStartDate: string | null;
  breedingEndDate: string | null;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  initialQty: number | null;
  currentQty: number | null;
  lockFlag: string;
  weaningQty: number | null;
  cullingQty: number | null;
  breedingStopNo: string;
  breedingRealEndDate: string | null;

  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  penGuid: string;

  matingStartDate: string | null;
  matingEndDate: string | null;
  weaningStartDate: string | null;
  weaningEndDate: string | null;
}

export interface SowAbortion {
  id: number;
  farmGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  sowGuid: string;
  recordDisease: string;
  lastStatus: string;
  lastResult: string;
  parity: number | null;
  breeding2Sow: Breeding2Sow[]
  
}
export interface SowBodyCondition {
  id: number;
  farmGuid: string;
  breedingGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  breeding2Sow: Breeding2SowBodyCondition[]
}
export interface SowFarrow {
  id: number;
  farmGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  sowGuid: string;
  farrowDate: string | null;
  farrowTime: string;
  farrowNo: string;
  farrowWeight: number | null;
  qtyTotal: number | null;
  qtyALive: number | null;
  qtyMummy: number | null;
  qtyStillbirth: number | null;
  qtyCulling: number | null;
  cullingReason: string;
  diseaseGuid: string;
  medicineGuid: string;
  farrowWeightDate: any;
  breeding2Sow: Breeding2Suckling[]
}

export interface SowFoster {
  id: number;
  farmGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  sowGuid: string;

  breeding2Sow: Breeding2Suckling[]
}

export interface SowHeating {
  id: number;
  farmGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  breeding2Sow: Breeding2SowIn[]
}

export interface SowMating {
  id: number;
  farmGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  breeding2Sow: Breeding2Sow[]
}

export interface SowPreFarrow {
  id: number;
  farmGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  breeding2Sow: Breeding2Sow[]
}
export interface SowPregnancyTest {
  id: number;
  farmGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  breeding2Sow: Breeding2SowIn[]
}

export interface SowWeaning {
  id: number;
  farmGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  sowGuid: string;
  weaningDate: any;

  breeding2Sow: Breeding2Sow[]
}
export interface SucklingCastration {
  id: number;
  farmGuid: string;
  sowGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  breeding2Suckling: Breeding2Suckling[];

}
export interface SucklingCutEar {
  id: number;
  farmGuid: string;
  sowGuid: string;
  breedingGuid: string;
  recordGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  breeding2Suckling: Breeding2Suckling[];
}
export interface SucklingCutTeethTail {
  id: number;
  sowGuid: string;
  farmGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  breeding2Suckling: Breeding2Suckling[];
}
export interface SucklingIronInjection {
  id: number;
  sowGuid: string;
  farmGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  breeding2Suckling: Breeding2Suckling[];
}

export interface SucklingMove {
  id: number;
  farmGuid: string;
  sowGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  breeding2Suckling: Breeding2Suckling[];
}
export interface SucklingTeachingSlot {
  id: number;
  farmGuid: string;
  sowGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  breeding2Suckling: Breeding2Suckling[];
}
export interface SucklingWeaning {
  id: number;
  farmGuid: string;
  sowGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  breeding2Suckling: Breeding2Suckling[];
}

export interface SucklingWeighing {
  id: number;
  farmGuid: string;
  sowGuid: string;
  breedingGuid: string;
  executeDate: any| null;
  executeReason: string;
  executeGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  breeding2Suckling: Breeding2Suckling[];
}
