// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class DeviceUser
    {
        public decimal Id { get; set; }
        public string Token { get; set; }
        public decimal? UserId { get; set; }
        public string Osname { get; set; }
        public string OsVersion { get; set; }
        public string DeviceName { get; set; }
        public string ModelName { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}