// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class NotificationUser
    {
        public decimal Id { get; set; }
        public string Title { get; set; }
        public string NotificationImage { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public bool? IsSeen { get; set; }
        public DateTime? SendDate { get; set; }
        public decimal? UserSendId { get; set; }
        public decimal? UserReciveId { get; set; }
    }
}