// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class Role
    {
        public decimal Id { get; set; }
        public string RoleName { get; set; }
        public string Comment { get; set; }
        public string Guid { get; set; }
    }
}