import { Injectable } from '@angular/core'
import { BreedingModule } from './breeding.module'

export * from './breeding/breeding.component'
export * from './breeding/breeding-bottom/breeding-bottom.component'
export * from './breeding/breeding-bottom/mating-room/mating-room.component'
export * from './breeding/breeding-bottom/pregnancy-room/pregnancy-room.component'
export * from './breeding/breeding-bottom/farrowing-room/farrowing-room.component'
export * from './breeding/breeding-bottom/general-record/general-record.component'
export * from './breeding/breeding-bottom/breeding-modal/breeding-modal.component'
export * from './breeding/breeding-bottom/breeding-detail-modal/breeding-detail-modal.component'
export * from './breeding/breeding-bottom/breeding-take-care-modal/breeding-take-care-modal.component'

export * from './breeding-sow-heating/breeding-sow-heating.component'
export * from './breeding-sow-mating/breeding-sow-mating.component'
export * from './breeding-sow-pick/breeding-sow-pick.component'
export * from './breeding-sow-pregnancy-test/breeding-sow-pregnancy-test.component'

export * from './breeding2/breeding2.component'
export * from './breeding2/breeding2-sow-in/breeding2-sow-in.component'
export * from './breeding2/breeding-detail/breeding-detail.component'
export * from './breeding2/breeding-sow-in/breeding-sow-in.component'
export * from './breeding-sow-in/breeding-sow-in.component'
export * from './breeding-sow/breeding-sow.component'
export * from './sow-body-condition/sow-body-condition.component'
export * from './sow-farrow/sow-farrow.component'
export * from './sow-foster/sow-foster.component'
export * from './sow-heating/sow-heating.component'
export * from './sow-mating/sow-mating.component'
export * from './sow-prefarrow/sow-prefarrow.component'
export * from './sow-pregnancy-test/sow-pregnancy-test.component'
export * from './sow-weaning/sow-weaning.component'
export * from './sow-in/sow-in.component'

export * from './common/breeding2-sow/breeding2-sow.component'
export * from './common/breeding2-sow-in/breeding2-sow-in.component'
