// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.DTO
{
    public partial class RoleDetailDto
    {
        public decimal Id { get; set; }
        public string UpperGuid { get; set; }
        public string PermissionName { get; set; }
        public string MenuName { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
    }
}