name: .NET Core CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --no-restore --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and publish API
      run: dotnet publish ./EvseProject -o $(Build.ArtifactStagingDirectory)/api

    - name: Build and publish Angular app
      run: |
        cd ./EvseProject
        npm ci
        npm run build -- --prod --output-path $(Build.ArtifactStagingDirectory)/app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: my-web-app
        package: $(Build.ArtifactStagingDirectory)/**/*.zip
